sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t raigen/rpi-alpine-python .
# test image
- docker run raigen/rpi-alpine-python python --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV PYTHON_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag raigen/rpi-alpine-python raigen/rpi-alpine-python:$TAG
    docker push raigen/rpi-alpine-python:$TAG
    docker push raigen/rpi-alpine-python
  fi
